# Configuraci贸n para Railway (PostgreSQL)

# Este archivo contiene la configuraci贸n necesaria para desplegar la base de datos PostgreSQL en Railway

# Variables de entorno para Railway
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres_password
POSTGRES_DB=nextjs_microservices

# Configuraci贸n de la base de datos
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}

# Configuraci贸n de Prisma para Railway
PRISMA_CLIENT_ENGINE_TYPE=binary
