name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build

      - name: Prepare deploy files
        run: |
          # 1. Crear carpeta deploy
          mkdir deploy
          
          # 2. Copiar standalone completo
          cp -r .next/standalone/* deploy/
          
          # 3. Copiar archivos de configuración
          cp .htaccess deploy/
          cp ecosystem.config.js deploy/
          [ -f .env ] && cp .env deploy/ || true
          
          # 4. Copiar static y server
          mkdir -p deploy/.next/{server,static}
          cp -r .next/static/* deploy/.next/static/
          cp -r .next/server/* deploy/.next/server/
        
      - name: Deploy to production
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          port: 21
          local-dir: ./deploy/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
