name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Clean production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 65002
          debug: true
          script: |
            pwd
            whoami
            echo "Testing SSH connection"
        
      - name: Deploy to production
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          port: 21
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
            .gitignore
            .github/**
            src/**
            public/**
            tsconfig.json
            jest.config.js
            .eslintrc.json
            
      - name: Execute post-deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 65002
          script: |
            chmod 755 server.js
            chmod 644 .htaccess
            chmod 644 .env
            pm2 reload all
