name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Clean remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 65002
          script: |
            cd /home/u396608776/domains/uno14.trading/public_html
            rm -rf .next/
            rm -rf node_modules/
            find . -maxdepth 1 ! -name '.env' ! -name '.' ! -name '..' -exec rm -rf {} +
        
      - name: Deploy to production
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          port: 21
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.next/**
            README.md
            .gitignore
            .env*
            .eslintrc*
            jest.config.js
            tsconfig.json
            
      - name: Execute post-deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 65002
          script: |
            cd /home/u396608776/domains/uno14.trading/public_html
            npm install --production
            pm2 delete all || true
            pm2 start ecosystem.config.js
            chmod 755 server.js
            chmod 644 .htaccess
            chmod 644 .env

      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 65002
          script: |
            cd /home/u396608776/domains/uno14.trading/public_html
            pm2 list
            curl http://localhost:3000/api/health
