name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Initialize npm in root
      run: |
        npm init -y
        npm install --legacy-peer-deps
    
    - name: Install Dependencies
      run: |
        for d in *-service/; do
          if [ -f "$d/package.json" ]; then
            echo "Installing dependencies for $d"
            cd $d
            npm install --legacy-peer-deps
            cd ..
          fi
        done
    
    - name: Debug npm
      if: failure()
      run: |
        echo "NPM Version:"
        npm -v
        echo "Node Version:"
        node -v
        echo "Package contents:"
        cat frontend-service/package.json
    
    - name: Start Services
      run: |
        chmod +x ./start_services.sh
        ./start_services.sh
        # Mostrar procesos Node.js
        echo "Procesos Node.js activos:"
        ps aux | grep node
        # Mostrar puertos en uso
        echo "Puertos en uso:"
        netstat -tulpn | grep LISTEN
        # Mostrar logs de servicios
        echo "Logs de servicios:"
        tail -n 50 logs/*.log
    
    - name: Prepare Test Environment
      run: |
        mkdir -p logs
        touch logs/integration_tests.log
        chmod 666 logs/integration_tests.log
        # Verificar conectividad
        for port in 3000 3001 3002 3003; do
          echo "Verificando puerto $port:"
          curl -v http://localhost:$port/health || true
        done
    
    - name: Run Tests
      run: |
        chmod +x ./run_direct_tests.sh
        ./run_direct_tests.sh
    
    - name: Stop Services
      if: always()
      run: |
        chmod +x ./stop_services.sh
        ./stop_services.sh

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    
    - name: Deploy to Server
      run: |
        scp -r . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.DEPLOY_PATH }} && chmod +x setup_server.sh && ./setup_server.sh"